const dotenv = require("dotenv");

dotenv.config();

const JWT_SECRET_ACCESS_TOKEN = process.env.JWT_SECRET_ACCESS_TOKEN;
const JWT_SECRET_REFRESH_TOKEN = process.env.JWT_SECRET_REFRESH_TOKEN;
const ACCESS_TOKEN_EXPIRED_TIME = process.env.ACCESS_TOKEN_EXPIRED_TIME;
const REFRESH_TOKEN_EXPIRED_TIME = process.env.REFRESH_TOKEN_EXPIRED_TIME;
const INVITATION_ACCESS_TOKEN_EXPIRED_TIME =
  process.env.INVITATION_ACCESS_TOKEN_EXPIRED_TIME;
const MESSAGE_BROKER = process.env.MESSAGE_BROKER;
const VALKEY_HOST = process.env.VALKEY_HOST;
const FLASK_ENDPOINT_URL = process.env.FLASK_ENDPOINT_URL;
const REACT_ENDPOINT_URL = process.env.REACT_ENDPOINT_URL;
const ALLOWED_ORIGINS = process.env.ALLOWED_ORIGINS;
const PORT = process.env.PORT;
const CRYPTO_SECRET_KEY = process.env.CRYPTO_SECRET_KEY;
const FIREBASE_PRIVATE_KEY_BASE64 = process.env.FIREBASE_PRIVATE_KEY_BASE64;
const MAILER_USER = process.env.MAILER_USER;
const MAILER_PASS = process.env.MAILER_PASS;

module.exports = {
  JWT_SECRET_ACCESS_TOKEN,
  JWT_SECRET_REFRESH_TOKEN,
  ACCESS_TOKEN_EXPIRED_TIME,
  REFRESH_TOKEN_EXPIRED_TIME,
  INVITATION_ACCESS_TOKEN_EXPIRED_TIME,
  MESSAGE_BROKER,
  VALKEY_HOST,
  FLASK_ENDPOINT_URL,
  REACT_ENDPOINT_URL,
  ALLOWED_ORIGINS,
  PORT,
  FIREBASE_PRIVATE_KEY_BASE64,
  CRYPTO_SECRET_KEY,
  MAILER_USER,
  MAILER_PASS,
};
